services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  # Register EasyAdmin controllers so they become services
  Dadoush\DynamicPageBundle\Controller\EasyAdmin\:
    resource: '../../../Controller/EasyAdmin/*Controller.php'
    public: true
    tags: ['controller.service_arguments']