version: '3.8'

services:
  # PHP-FPM container for running Symfony
  php:
    build:
        context: .
        dockerfile: php/Dockerfile
    container_name: symfony_php
    working_dir: /srv/app
    volumes:
      - ../src:/srv/app:delegated
      - ../packages:/srv/packages:delegated
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      # match these to your .env in Symfony
      SYMFONY_ENV: dev
    networks:
      - symfony

  # Nginx to serve PHP-FPM
  web:
    image: nginx:alpine
    container_name: symfony_nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ../src:/srv/app:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - symfony

  # MySQL database
  db:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonypass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
    driver: bridge
